spring.application.name=devop7303
server.servlet.context-path=/devop7303
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.url=jdbc:mysql://51.89.254.255:3306/kyvifbzf_devop
#spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_devop2024
#spring.datasource.username=freedb_devopuser
#spring.datasource.password=cnk!d%EW4SJW7bM
#local
spring.datasource.url=jdbc:mysql://localhost:3306/freedb_devop2024
spring.datasource.username=bountydbuser
spring.datasource.password=@Thunder101
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health, info, logfile
management.endpoint.logfile.external-file = /opt/devoplog/log.log


