SPRING_APPLICATION_NAME=devop7303
SERVER_SERVLET_CONTEXT-PATH=/devop7303
SERVER_PORT=2025
SPRING_JPA_HIBERNATE_DDL-AUTO=update
SPRING_DATASOURCE_URL=
SPRING_DATASOURCE_USERNAME=
SPRING_DATASOURCE_PASSWORD=


SPRINGDOC_SWAGGER-UI_PATH=/swagger-ui.html
MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health, info, logfile
MANAGEMENT_ENDPOINT_LOGFILE_EXTERNAL-FILE=/opt/devoplog/log.log

SPRING_MAIL_HOST=smtp.gmail.com
SPRING_MAIL_PROTOCOL=smtp
SPRING_MAIL_PORT=587
SPRING_MAIL_USERNAME=nwokochibuokem@gmail.com
SPRING_MAIL_PASSWORD= mhwz mwna lcqz woda
SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true


