FROM maven:3.8.6-eclipse-temurin-17 AS build

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk AS runtime

COPY --from=build /app/target/*.jar DEVOP7303.jar

EXPOSE 2025

ENTRYPOINT ["java", "-jar", "DEVOP7303.jar"]